DROP TABLE IF EXISTS T_USER;
DROP TABLE IF EXISTS T_POST;

CREATE TABLE T_USER (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL
);

CREATE TABLE T_POST (
    POST_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTHOR_ID INTEGER NOT NULL,
    CRT_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    POST_TITLE TEXT NOT NULL,
    POST_BODY TEXT NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES T_USER (USER_ID)
);

